# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

title: Fred Blogs
subtitle: "A place for ideas, experiences and interesting thoughts..."
name: "Freddie Leadsom"
email: fleadsom@me.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Freddie: a Software Engineer, Data Science enthusiast, amateur Crossfit
  athlete and traveller. This blog is to share ideas, useful experiences and inspiration
  with fellow aspiring masters of the universe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fleadsom.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  fleadsom
linkedin_username: fleadsom

# Minimal Mistakes theme https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/
# Configuration notes here https://mmistakes.github.io/minimal-mistakes/docs/configuration/

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
include: ["_posts", "_pages"]

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/fleadsom/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fleadsom"

# Author sidebar
author:
  name     : "Freddie Leadsom"
  avatar   : "/assets/images/profile.jpeg"
  bio      : "Hi! I'm Freddie. I'm a Software Engineer, Data Science enthusiast,
  hobbyist Crossfitter/functional athlete and traveller. This blog is to share ideas, useful experiences and inspiration
  with fellow aspiring masters of the universe.
  Please email me or find me on LinkedIn!"
  email: "fleadsom@me.com"
  location : "London, UK"
